[package]
name = "RESTful"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.0", features = ["mysql", "chrono", "r2d2"] }
chrono = { version = "0.4.24", features = ["serde"] }
dotenvy = "0.15"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
